### PR TITLE
Minor fixes for W3C validation

### PR DESCRIPTION
**Pull request by tompollard**
The site should not raise errors or warnings when run through https://validator.w3.org/

This fixes the remaining issues on all pages except the publications page (/publications). I'm not entirely sure how this content is generated, so left that for now.

- replace name tag with the id tag for internal links
- set the images on the people page to a fix pixel width (rather than %)
- remove the unnecessary `role="main"` from the news page

### CODE REVIEW

**Comment by elfeto** [comment]
You caught `change.py` in your PR, please remove it :)

**Comment by Lucas-Mc** [comment]
'change.py' has been modified before if you look at the git blame.. it shouldn't matter if it's just the HTML inside the quotes right?

**Comment by tompollard** [comment]
> You caught change.py in your PR, please remove it :)

That was intentional, but that file is likely to be reviewed anyway, so I can remove it for now!

**Comment by elfeto** [comment]
I am unsure if the file itself is there... but until we replace the entire way we do publications, we \*should\* not touch publications nor lcp_references

**Comment by tompollard** [comment]
Done! Squashed to single commit. The changes don't touch publications, lcp_references, etc.

**Comment by elfeto** [comment]
Thanks! :) is that the `change.py` will break if you look at it badly :p

**Pull request merged**
