### PR TITLE
Cleans publication updates

### PR DESCRIPTION
**Pull request by Lucas-Mc**
Automatically removes the file used to update the publications after it has been updated in the templates. Removes extra publications HTML file which was symlinked to the templates folder. Moves `shasum.references` to the static folder.

### CODE REVIEW

**Comment by elfeto** [comment]
Since @tompollard  was keen on taking charge of the last changes of the `change.py` I will leave this to him too, but I have a ssimple question, why do you set the shasum in static?

**Comment by Lucas-Mc** [comment]
I wasn't sure where else to put it, and it's not static so it doesn't make the most sense but it's also not a template... should we just leave it in the top directory?

**Comment by elfeto** [comment]
yea just leave it where it was, because static is public to the world, and it makes to sense to make that file public.

**Comment by tompollard** [comment]
I didn't look closely at the changes, but just didn't want to leave the pr sitting around for too long (easy to change things back if we need to). Is the shasum still needed? If we are tracking the project in git, couldn't we use git diffs to see whether a file has changed?

**Comment by Lucas-Mc** [comment]
What is the issue if it runs and the file hasn't changed? Shouldn't it just re-write the file with the same contents?

**Comment by elfeto** [comment]
I have to reacquaintance myself with this script, but its one of 2 options:
 1. It re-writes the same thing (which then why have the shasum)
 2. It skips the edit since its the latest version (which is the thing I think it does)

@tompollard  If you want to change the way the `change.py` uses the shasum and use git instead make sure both shasums are calculated equally and go for it, in that case we wont need it.

**Comment by tompollard** [comment]
> @tompollard If you want to change the way the change.py uses the shasum and use git instead make sure both shasums are calculated equally and go for it, in that case we wont need it.

Whatever works is good on my side! The simpler the better. I'm not sure whether relying on git is simpler or more complicated, but we probably only want one or the other (i.e. either a checksum or git, but not both). 

I did wonder whether it might be easiest to just not track the sitedata folder in git. Maybe we could try with git and then switch back to checksums later if git doesn't work out?

**Comment by elfeto** [comment]
>I did wonder whether it might be easiest to just not track the sitedata folder in git.

You mean the folder with news.yml and people.yml ?
I think is better to track it in case someone changes their BIO or something changes, it might be easier/useful to know who and what was changed.

>Maybe we could try with git and then switch back to checksums later if git doesn't work out?

If it's the same to you, then why not keep the thing we have working? or even simpler, calculate it at the moment `change.py` is ran, and that way we do'nt have to keep track of the file nor spend time figuring out how to fix this unbroken thing using git.

**Comment by Lucas-Mc** [comment]
> If it's the same to you, then why not keep the thing we have working? or even simpler, calculate it at the moment `change.py` is ran, and that way we do'nt have to keep track of the file nor spend time figuring out how to fix this unbroken thing using git.

I like this idea a lot.

**Comment by tompollard** [comment]
> You mean the folder with news.yml and people.yml ? I think is better to track it in case someone changes their BIO or something changes, it might be easier/useful to know who and what was changed.

Yep, that folder. Sounds good to me.

> If it's the same to you, then why not keep the thing we have working? or even simpler, calculate it at the moment change.py is ran, and that way we do'nt have to keep track of the file nor spend time figuring out how to fix this unbroken thing using git.

Whatever you both decide is good. Ideally the publications file should be in the sitedata/ folder, so that all of the data used in the site is in one place, and updating news, people, publications should be a similar process from a user perspective (e..g make news, make publications, etc).

**Comment by tompollard** [comment]
@Lucas-Mc are you able to run change.py with `./change.py`? This doesn't work for me. Changing the shebang to use a virtual environment is good, but I think the shebang needs to be the first line in the file (i.e. `# -*- coding: UTF-8 -*-` needs to go somewhere else). Please could you add a brief explanation of what is supposed to happen when change.py is run?

**Comment by Lucas-Mc** [comment]
`change.py`:

1. Takes `lcp_references.html` as an input
2. Generates the updated `publications.html` and `recent_publications.html`

**Comment by tompollard** [comment]
thanks, had a quick play around. looks good to me!

**Pull request merged**
